### ISSUE TITLE
How to mutation?

### ISSUE THREAD

**Issue by AAIING** [DirkWolthuis/graphql-express-migrating-mysql#2]
Hi

I have problem with apply mutation , my code is

`extend type Mutation{
        changeStatusPedido(id_evento: ID!, estado_pedido: String): [Evento!]
    }`

`type Evento {
        id_evento: ID!
        nombre_evento: String
        fecha: String
        hora_inicio: String
        hora_termino: String
        estado_pedido: String
        precio_entrada: Int
        direccion_evento: String
        lat_evento: String
        lng_evento: String
        descripcion_evento: String
        id_empresa: ID!
    }`

`Mutation:{
        changeStatusPedido: async (obj, args,  context, info) =>{
            try{
                let response = await  db.evento.update({estado_pedido: args.estado_pedido},
                    { where:{ id_evento: args.id_evento }})
                return response;
                }catch(error){
                    throw error;
                }

        
        }
     },`

LOG: 
Executing (default): UPDATE `evento` SET `estado_pedido`=? WHERE `id_evento` = ?

the problem is graphql don't bind variables in query

**Comment by wangtoday** [comment]
Hi Mate,

Below is my Demo, 


`import { gql } from 'apollo-server-express'
import * as db from '../database'

export const typeDefs = gql`
    extend type Query {
        users: [User]
        user(id: ID!): User
    }

    type Mutation {
        createUser(id: ID!, email: String!,name:String!): User!
        updateUser(id:ID!):String
    }


    type User {
        id: ID!
        email: String
        name: String
    }
`

export const resolvers = {
    Query: {
        users: async () => db.users.findAll(),
        user: async (obj, args, context, info) => db.users.findByPk(args.id),
    },
    Mutation: {
        // 1
        updateUser: async (parent, args) => {
            return db.users.update({ name: 'new name whatever' }, { where: { id: args.id } }).then(value=>"haha")
        },
        // 2
        createUser: async (parent, args) => {
            console.log('----: ', args, parent)
            return db.users.create({
                id: args.id,
                name: args.name,
                email: args.email,
            }).then(value => {
                console.log(value, args)
                return args
            })
        },
    },
}

// mutation CreateReviewForEpisode($ep: Episode!, $review: ReviewInput!) {
//     createReview(episode: $ep, review: $review) {
//         stars
//         commentary
//     }
// }
`

It worked well on my side.
